#!/usr/bin/env bash
set -euo pipefail

# versions.sh
# Generate content/versions.md from a template and sbom inputs.
# Usage: scripts/versions.sh --tag <tag> [--image <image>] [--sbom <sbom>] [--sbom-base64 <base64>] [--template <tmpl>] [--out <out>]

usage() {
  cat <<EOF
Usage: $0 --tag <tag> [--image <image>] [--sbom <sbom>] [--sbom-base64 <base64>] [--template <tmpl>] [--out <out>]

Defaults:
  image: ghcr.io/stakater/reloader-enterprise
  template: templates/version.md.tmpl
  out: content/versions.md

The script decodes base64 SBOM when provided and prefers it over raw --sbom.
EOF
}

TAG=""
IMAGE="ghcr.io/stakater/reloader-enterprise"
IMAGE_UBI=""
SBOM=""
SBOM_BASE64=""
TEMPLATE="templates/version.md.tmpl"
OUT="content/versions.md"
RELEASE_BASE="https://github.com/stakater/Reloader/releases/tag"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--tag) TAG="$2"; shift 2 ;;
  -i|--image) IMAGE="$2"; shift 2 ;;
  --image-ubi) IMAGE_UBI="$2"; shift 2 ;;
    --sbom) SBOM="$2"; shift 2 ;;
    --sbom-base64) SBOM_BASE64="$2"; shift 2 ;;
    --template) TEMPLATE="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
  --release-base) RELEASE_BASE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

if [ -z "$TAG" ]; then
  echo "--tag is required" >&2
  usage
  exit 2
fi

# If SBOM_BASE64 provided, try to decode (strip whitespace/newlines first)
if [ -n "$SBOM_BASE64" ]; then
  CLEANED=$(printf "%s" "$SBOM_BASE64" | tr -d '\n' | tr -d '\r' | tr -d ' ')
  # Use a safe temp file in /tmp with $$ to avoid collisions
  TMPFILE=$(mktemp /tmp/decoded_sbom.XXXXXX)
  if printf "%s" "$CLEANED" | base64 -d > "$TMPFILE" 2>/dev/null; then
    SBOM=$(cat "$TMPFILE")
    rm -f "$TMPFILE"
  else
    rm -f "$TMPFILE" || true
    echo "Warning: failed to decode SBOM_BASE64; falling back to provided --sbom (if any)" >&2
  fi
fi

# Build release URL
RELEASE_URL="${RELEASE_BASE}/${TAG}"

# Compute UBI image handling:
# If user provided --image-ubi, use that as base for the UBI image; otherwise we'll append the '-ubi' suffix to the tag.
if [ -n "$IMAGE_UBI" ]; then
  IMAGE_UBI_BASE="$IMAGE_UBI"
  IMAGE_UBI_WITH_TAG="${IMAGE_UBI_BASE}:${TAG}-ubi"
else
  IMAGE_UBI_BASE="$IMAGE"
  IMAGE_UBI_WITH_TAG="${IMAGE}:${TAG}-ubi"
fi

# Render single entry to temp file
ENTRY_TMP=$(mktemp)
# compute image with tag
IMAGE_WITH_TAG="${IMAGE}:${TAG}"
# NOTE: IMAGE_UBI_WITH_TAG and IMAGE_UBI_BASE already computed above
# If SBOM content exists, write it to a temp file so awk can insert it (preserves newlines)
SBOM_FILE=""
if [ -n "$SBOM" ]; then
  SBOM_FILE=$(mktemp)
  # If the provided SBOM looks like a path to an existing file, copy its contents; otherwise write the SBOM string
  if [ -f "$SBOM" ]; then
    cat "$SBOM" > "$SBOM_FILE"
  else
    printf '%s' "$SBOM" > "$SBOM_FILE"
  fi
fi
if [ -f "$TEMPLATE" ]; then
  export IMAGE="$IMAGE" IMAGE_WITH_TAG="$IMAGE_WITH_TAG" IMAGE_UBI_BASE="$IMAGE_UBI_BASE" IMAGE_UBI_WITH_TAG="$IMAGE_UBI_WITH_TAG" VERSION="$TAG" SBOM RELEASE_URL
  if command -v envsubst >/dev/null 2>&1; then
    envsubst < "$TEMPLATE" > "$ENTRY_TMP"
  else
    # Fallback: use sed to perform placeholder replacement. SBOM (multiline) is inserted by reading a temp file.
    # Prepare sed-safe replacements (escape / and &)
    esc() { printf '%s' "$1" | sed -e 's/[\/&]/\\&/g'; }
  iwt_esc=$(esc "$IMAGE_WITH_TAG")
  img_esc=$(esc "$IMAGE")
  ubi_base_esc=$(esc "$IMAGE_UBI_BASE")
  ubi_iwt_esc=$(esc "$IMAGE_UBI_WITH_TAG")
    ver_esc=$(esc "$TAG")
    rel_esc=$(esc "$RELEASE_URL")

  SED_SCRIPT=$(mktemp)
  cat > "$SED_SCRIPT" <<EOF
s|\\${IMAGE_WITH_TAG}|$iwt_esc|g
s|\\${IMAGE}|$img_esc|g
s|\${IMAGE_UBI_WITH_TAG}|$ubi_iwt_esc|g
s|\${IMAGE_UBI_BASE}|$ubi_base_esc|g
s|\\${VERSION}|$ver_esc|g
s|\\${RELEASE_URL}|$rel_esc|g
/\\${SBOM}/ {
r $SBOM_FILE
d
}
EOF
    sed -f "$SED_SCRIPT" "$TEMPLATE" > "$ENTRY_TMP"
    sed_exit=$?
    rm -f "$SED_SCRIPT"
    if [ $sed_exit -ne 0 ]; then
      echo "ERROR: failed to render template with sed" >&2
      [ -n "$SBOM_FILE" ] && rm -f "$SBOM_FILE"
      exit 2
    fi
  fi
else
  echo "ERROR: template not found: $TEMPLATE" >&2
  exit 2
fi

# Read existing history into a temp file and strip top-level header and any footer lines
EXISTING_TMP=$(mktemp)
if [ -f "$OUT" ]; then
  if head -n1 "$OUT" | grep -q '^# Reloader Enterprise'; then
    tail -n +2 "$OUT" > "$EXISTING_TMP"
    # remove an empty first line if present
    sed -i '1{/^$/d;}' "$EXISTING_TMP"
  else
    cat "$OUT" > "$EXISTING_TMP"
  fi
  # Remove any existing footer lines containing 'Generated by automation' (handles HTML or plain text)
  sed -i -E '/Generated by automation/d' "$EXISTING_TMP"
else
  # ensure file exists but empty
  : > "$EXISTING_TMP"
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUT")"

## Clean the generated entry of any footer markers so the footer appears only once at the end
ENTRY_CLEAN_TMP=$(mktemp)
# remove any footer markers (HTML or plain) from the generated entry
sed -E '/Generated by automation/d' "$ENTRY_TMP" > "$ENTRY_CLEAN_TMP"

# Write final file: header + new entry + existing + single footer
{
  printf '# Reloader Enterprise – Release History\n\n'
  cat "$ENTRY_CLEAN_TMP"
  # if existing not empty, separate with a blank line
  if [ -s "$EXISTING_TMP" ]; then
    printf '\n'
    cat "$EXISTING_TMP"
  fi
  # single footer at the end (match the template's small/italic form if present)
  printf '<small><i>Generated by automation</i></small>\n'
} > "$OUT"

# cleanup temps
rm -f "$ENTRY_TMP" "$ENTRY_CLEAN_TMP" "$EXISTING_TMP"
# cleanup SBOM temp file
[ -n "$SBOM_FILE" ] && rm -f "$SBOM_FILE"

echo "Wrote $OUT"
