name: Auto approve
on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'stakater-user' && contains(join(github.event.pull_request.labels.*.name, ' '), 'version-bump')
    steps:
      - uses: hmarr/auto-approve-action@v4